import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { AGENT_NAME, BROKERAGE_NAME, CONTACT_EMAIL, CURRENT_YEAR } from '../constants/compliance';

export default function Terms() {
  return (
    <div className="min-h-screen bg-cream">
      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-16 pb-24 md:pb-16">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <span className="section-tag mb-4 block">legal</span>
          <h1 className="font-serif text-4xl sm:text-5xl text-ink mb-2">Terms of Use</h1>
          <p className="text-ink4 font-sans text-sm mb-12">Last updated: May 2025</p>
        </motion.div>

        <div className="space-y-10 text-sm font-sans text-ink2 leading-relaxed">
          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Nature of service</h2>
            <p>PropertyLens is an AI-powered real estate information platform operated by {AGENT_NAME}, Salesperson, {BROKERAGE_NAME}. PropertyLens is not a brokerage. It does not provide brokerage services, representation agreements, or transaction services through this website.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">AI valuations</h2>
            <p>Automated valuations, CMAs, and market analyses generated by this platform are estimates based on available data. They are not certified appraisals under the Canadian Uniform Standards of Professional Appraisal Practice (CUSPAP) and must not be relied upon as such for financing, legal, or any other professional purpose.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">MLS data</h2>
            <p>Listing data is provided under license from the Toronto Regional Real Estate Board (TRREB) and the Canadian Real Estate Association (CREA). The trademarks MLS®, REALTOR®, and the associated logos are owned by CREA. You may not scrape, reproduce, redistribute, or use listing data for any commercial purpose without express written permission.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Investment projections</h2>
            <p>Investment return estimates, rental yield calculations, cap rates, and cash flow projections are illustrative only and based on assumed variables. They do not constitute financial advice and are not guarantees of future performance. Consult a licensed financial advisor before making investment decisions.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Mortgage calculations</h2>
            <p>Mortgage calculators and stress test results on this platform are for illustrative purposes only. They do not constitute a mortgage pre-approval, commitment, or financial advice. Consult a licensed mortgage professional.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Limitation of liability</h2>
            <p>PropertyLens and {AGENT_NAME} are not liable for decisions made based on AI-generated estimates, market data, or any content on this platform. The information is provided "as is" without warranties of accuracy, completeness, or fitness for a particular purpose.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Prohibited use</h2>
            <ul className="space-y-2">
              {[
                'Scraping or automated harvesting of listing data',
                'Republishing MLS data without authorization',
                'Using the platform for spam, fraud, or misrepresentation',
                'Reverse engineering the AI system',
              ].map(item => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-ink4 mt-1">—</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Governing law</h2>
            <p>These Terms are governed by the laws of the Province of Ontario, Canada. Any disputes shall be resolved in the courts of Ontario.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-ink mb-3">Contact</h2>
            <p>Questions about these Terms: <a href={`mailto:${CONTACT_EMAIL}`} className="text-green underline">{CONTACT_EMAIL}</a></p>
          </section>

          <div className="bg-cream2 rounded-xl p-5 text-[11px] text-ink4">
            <p>© {CURRENT_YEAR} PropertyLens · {AGENT_NAME}, {BROKERAGE_NAME}</p>
            <p className="mt-1">Governing law: Province of Ontario, Canada</p>
            <p className="mt-1">
              <Link to="/privacy" className="underline">Privacy Policy</Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
